# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AWaI6jrN56rzpKdO1yH9vkLAV70eoqf9
"""

from flask import Flask, jsonify, request
import boto3
from flask_cors import CORS

app = Flask(__name__)
CORS(app) 

@app.route("/translation", methods=["POST"])
def tran():
  request_data = request.get_json()
  txt = request_data["text"]
  lang_dict = request_data["language"]
  t_lang = {'Afrikaans': 'af', 'Albanian': 'sq', 'Amharic': 'am',
                       'Arabic': 'ar', 'Armenian': 'hy', 'Azerbaijani': 'az',
                       'Bengali': 'bn', 'Bosnian': 'bs', 'Bulgarian': 'bg',
                       'Catalan': 'ca', 'Chinese (Simplified)': 'zh',
                       'Chinese (Traditional)': 'zh-TW', 'Croatian': 'hr',
                       'Czech': 'cs', 'Danish': 'da ', 'Dari': 'fa-AF',
                       'Dutch': 'nl ', 'English': 'en', 'Estonian': 'et',
                       'Farsi (Persian)': 'fa', 'Filipino Tagalog': 'tl',
                       'Finnish': 'fi', 'French': 'fr', 'French (Canada)': 'fr-CA',
                       'Georgian': 'ka', 'German': 'de', 'Greek': 'el', 'Gujarati': 'gu',
                       'Haitian Creole': 'ht', 'Hausa': 'ha', 'Hebrew': 'he ', 'Hindi': 'hi',
                       'Hungarian': 'hu', 'Icelandic': 'is', 'Indonesian': 'id ', 'Italian': 'it',
                       'Japanese': 'ja', 'Kannada': 'kn', 'Kazakh': 'kk', 'Korean': 'ko',
                       'Latvian': 'lv', 'Lithuanian': 'lt', 'Macedonian': 'mk', 'Malay': 'ms',
                       'Malayalam': 'ml', 'Maltese': 'mt', 'Mongolian': 'mn', 'Norwegian': 'no',
                       'Persian': 'fa', 'Pashto': 'ps', 'Polish': 'pl', 'Portuguese': 'pt',
                       'Romanian': 'ro', 'Russian': 'ru', 'Serbian': 'sr', 'Sinhala': 'si',
                       'Slovak': 'sk', 'Slovenian': 'sl', 'Somali': 'so', 'Spanish': 'es',
                       'Spanish (Mexico)': 'es-MX', 'Swahili': 'sw', 'Swedish': 'sv',
                       'Tagalog': 'tl', 'Tamil': 'ta', 'Telugu': 'te', 'Thai': 'th',
                       'Turkish': 'tr', 'Ukrainian': 'uk', 'Urdu': 'ur', 'Uzbek': 'uz',
                       'Vietnamese': 'vi', 'Welsh': 'cy'}
  lang = t_lang[lang_dict]
  if lang_dict in t_lang:
    if len(txt)!=0:
      if len(txt)<=5000:
        translate = boto3.client('translate', aws_access_key_id="", 
                    aws_secret_access_key="", 
                    region_name="us-west-1")
        result = translate.translate_text(Text=txt,
                                        SourceLanguageCode="en",
                                        TargetLanguageCode=lang)
        translation = result.get('TranslatedText')
        return {"translation": translation}
      else:
        s = txt
        i = 0
        c=0 
        while i<len(s):
          if s[i] == ".":
            c+=1
          i+=1
        k=0
        i = 0
        a = []
        t=c//6
        p = t
        while i<len(s):
          if s[i] ==".":
            k+=1
          if k==p:
            a.append(i)
            p+=t
          i+=1 
        translate = boto3.client('translate', aws_access_key_id="AKIA2LPLQN2BX6NJ2ZHM", 
                          aws_secret_access_key="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", 
                          region_name="us-west-1")
        s1 = s[:a[0]+1]
        s2 = s[a[0]:a[1]+1]
        s3 = s[a[1]:a[2]+1]
        s4 = s[a[2]:a[3]+1]
        s5 = s[a[3]:a[4]+1]
        s6 = s[a[4]:]

        result1 = translate.translate_text(Text=s1,
                                              SourceLanguageCode="en",
                                          TargetLanguageCode=lang)
        result1 = result1.get('TranslatedText')   
        result2 = translate.translate_text(Text=s2,
                                              SourceLanguageCode="en",
                                              TargetLanguageCode=lang)
        result2 = result2.get('TranslatedText')
        result3 = translate.translate_text(Text=s3,
                                              SourceLanguageCode="en",
                                              TargetLanguageCode=lang)
        result3 = result3.get('TranslatedText')
        result4 = translate.translate_text(Text=s4,
                                              SourceLanguageCode="en",
                                              TargetLanguageCode=lang)
        result4 = result4.get('TranslatedText')
        result5 = translate.translate_text(Text=s5,
                                              SourceLanguageCode="en",
                                              TargetLanguageCode=lang)
        result5 = result5.get('TranslatedText')
        result6 = translate.translate_text(Text=s6,
                                              SourceLanguageCode="en",
                                              TargetLanguageCode=lang)
        result6 = result6.get('TranslatedText')
        translation = result1 + result2 + result3 + result4 + result5 + result6
        return {"translation": translation}
    else:
      return {"translation": "Empty text is provided for translation"}
  else:
    return {"translation": "Language is not supported"}
    
if __name__ == "__main__":
  app.run()
